name: Selenium Wake Up

on:
  schedule:
    - cron: '0 5,17 * * *' # 日本時間 14時と深夜2時
  workflow_dispatch:

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run Wake Up Script
        run: python wakeup.py
